rvm:
- 2.0.0
- 2.1
- 2.2
- 2.3

sudo: required

services: docker

env:
  matrix:
# CHEF_VERSION is only for unit tests, no for test-kitchen:
  - TESTS="style unit" CHEF_VERSION="~> 12.0"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration[default-oraclelinux-6,verify]"
  - TESTS="integration[lwrp-centos-6,verify]"
  - TESTS="integration[lwrp-scientific-66,verify]"
  - TESTS="integration[ohai-centos-6,verify]"
  - TESTS="integration[ohai-oraclelinux-6,verify]"
  - TESTS="integration[ohai-scientific-66,verify]"

matrix:
  exclude:
# Disable integration tests in old Ruby versions:
  - rvm: 2.0.0
    env: TESTS="integration[default-oraclelinux-6,verify]"
  - rvm: 2.1
    env: TESTS="integration[default-oraclelinux-6,verify]"
  - rvm: 2.3
    env: TESTS="integration[default-oraclelinux-6,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[lwrp-centos-6,verify]"
  - rvm: 2.1
    env: TESTS="integration[lwrp-centos-6,verify]"
  - rvm: 2.3
    env: TESTS="integration[lwrp-centos-6,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[lwrp-scientific-66,verify]"
  - rvm: 2.1
    env: TESTS="integration[lwrp-scientific-66,verify]"
  - rvm: 2.3
    env: TESTS="integration[lwrp-scientific-66,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[ohai-centos-6,verify]"
  - rvm: 2.1
    env: TESTS="integration[ohai-centos-6,verify]"
  - rvm: 2.3
    env: TESTS="integration[ohai-centos-6,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[ohai-oraclelinux-6,verify]"
  - rvm: 2.1
    env: TESTS="integration[ohai-oraclelinux-6,verify]"
  - rvm: 2.3
    env: TESTS="integration[ohai-oraclelinux-6,verify]"
  - rvm: 2.0.0
    env: TESTS="integration[ohai-scientific-66,verify]"
  - rvm: 2.1
    env: TESTS="integration[ohai-scientific-66,verify]"
  - rvm: 2.3
    env: TESTS="integration[ohai-scientific-66,verify]"

before_install:
- chef --version &> /dev/null || curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.18.30
- eval "$(/opt/chefdk/bin/chef shell-init bash)"

install:
- chef exec bundle install --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- ruby --version
- chef exec ruby --version
- chef --version
- cookstyle --version
- foodcritic --version

script: travis_retry chef exec bundle exec rake $TESTS
